services:
  - type: web
    name: tasker-api
    runtime: python
    buildCommand: python -m pip install --upgrade pip  && pip install .
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10 
      - key: PYTHONPATH
        value: .
      # AUTHENTICATION (Placeholder keys)
      - key: ACCESS_KEY
        sync: false
      - key: REFRESH_KEY
        sync: false
      - key: ACCESS_TOKEN_MAX_AGE
        value: "30" 
      - key: REFRESH_TOKEN_MAX_AGE
        value: "604800"
      - key: REFRESH_TOKEN_COOKIE_NAME
        value: refresh_token
      - key: REFRESH_TOKEN_DOMAIN
        value: .onrender.com

      # DATABASE (AIVEN)
      - key: DB_HOST
        value: mysql-taskerdb-kennmusyimi97-be49.i.aivencloud.com
      - key: DB_PORT
        value: "28497"
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: todo_schema

      # REDIS (UPSTASH)
      - key: REDIS_URL
        sync: false